Repository NavAbility/NavAbilitySDK.py, pull requests merged in 2023-05, with the labels that each got.

#120 Get tests running again by fixing or skipping
  src/navability/entities/factor/factor.py
  src/navability/entities/variable/variable.py
  src/navability/services/user.py
  src/navability/services/variable.py
  tests/conftest.py
  tests/test_factor.py
  tests/test_solver.py
  tests/test_variable.py
Labels: enhancement, CICD, bug fix

#127 make docs
  Makefile
Labels: documentation, enhancement

#128 add developer docs page
  docs/_toc.yml
  docs/developer.md
Labels: documentation, enhancement

#136 Test addVariable and addFactor and slightly better
  src/navability/services/factor.py
  src/navability/services/variable.py
  tests/test_blob.py
  tests/test_building_fg.py
Labels: CICD, bug fix, test all the things

#141 listBlobEntriesAsync pattern
  docs/bigexample.md
  src/navability/services/blobentry.py
Labels: enhancement

#142 add codecov badge to readme
  README.md
Labels: enhancement

#143 Use nest_asyncio for sync calls
  setup.py
  src/navability/services/blobentry.py
  src/navability/services/blobstore.py
  src/navability/services/factor.py
  src/navability/services/variable.py
Labels: enhancement

#144 updating docs variables page for v0.6
  Makefile
  docs/developer.md
  docs/variables.md
  src/navability/entities/dfgclient.py
  src/navability/services/variable.py
Labels: documentation, enhancement

#145 build docs twice for docstrings
  .github/workflows/documentation.yml
Labels: documentation, CICD

#147 make docs_cicd
  .github/workflows/documentation.yml
  Makefile
Labels: documentation, CICD

#148 better sphinx docstring autodocs support
  docs/_config.yml
  docs/getting-started.md
  docs/requirements.txt
  docs/variables.md
  src/navability/entities/variable/variable.py
  src/navability/services/variable.py
Labels: documentation, CICD

#150 fixed blobs entries docs page
  Makefile
  docs/blobs.md
  docs/variables.md
  src/navability/entities/blob/blobentry.py
  src/navability/entities/navabilityclient.py
  src/navability/services/blobentry.py
Labels: documentation

#151 getFactor when .data is b64 or not
  src/navability/entities/factor/factor.py
  src/navability/services/factor.py
Labels: bug fix, workaround

#153 fix sdkCommonGQL install copy
  MANIFEST.in
  Makefile
  docs/_toc.yml
  docs/bigexample.md
  docs/blobs.md
  docs/buildgraph.md
  docs/developer.md
  docs/getting-started.md
  docs/nvatutorials.md
  src/navability/services/loader.py
Labels: enhancement, dependencies

#154 fix install v0.6.0-1
  MANIFEST.in
  setup.py
Labels: bug fix, dependencies

#155 v0.6.0-1
  MANIFEST.in
  setup.py
Labels: release

#158 better setup comments
  setup.py
Labels: enhancement
